### ISSUE TITLE
(Logistics Mod) Item Senders will not push materials to production buildings built via blueprints

### ISSUE THREAD

**Issue by ghandye** [DeadMor0z/SatisfactoryMods#1]
There appears to be some kind of interaction bug between the Logistics mod for Satisfactory and the blueprint functionality introduced in Update 7. 

In short, any production building built via blueprint will not receive any items transmitted from any Item Sender.

Curious if others can reproduce.

Simple steps to reproduce on my system:

1) Feed iron ore into an Item Sender (e.g. hook up output of a miner on an iron deposit, straight into an item sender)

2) Slap down a Blueprint Designer, and create a blueprint with a single smelter, configured to produce Iron Ingots. Note how this smelter does fill up properly with Iron Ore even when inside the Blueprint Designer.

3) Name and save the blueprint (e.g. "Iron Smelter test")

4) Deploy the Iron Smelter test blueprint somewhere

5) (BUG) Note how the iron smelter placed via blueprint does not fill up with ore automatically

6) By contrast, note that you can build another iron smelter by hand right next to it, and it will fill up with ore automatically. 

The workaround is to build item receivers inside a blueprint and pipe belts from those into the inputs of machines, but who wants to do that? :-)

**Comment by DeadMor0z** [comment]
Looks like game does not fire any event on buildables when blueprint was build. Made a workaround for this. Should work in 1.1.1

**Comment by ghandye** [comment]
Confirmed fixed. Thanks a ton for the amazingly quick turnaround!
