### ISSUE TITLE
Sugestion to Fluid Sender

### ISSUE THREAD

**Issue by psmjunior** [DeadMor0z/SatisfactoryMods#11]
Sorry about my English.

So, my sugestion consists in non sendo fluid to a machine with a pipe conected.
For what?
For not stop a production, because fluid overflow on machine, such like water on refinary producign aluminum scrap, sending via pipe to a packager, but packager is receiving fron fluid sender to

**Comment by DeadMor0z** [comment]
Hi!
why do you put pipes to packager? I suggest do not connect any pipes to machines which can receive fluid via fluid sender. Fluid sender will controll fluid flow, it will put just enough for production to go on.
And put fluid sender on refinery, so it could distribute water it produces

**Comment by psmjunior** [comment]
Because I have to get rid of the water, but I have a lot of water on fluid senders/receiver, water of refinary don't go to senders, the refinary is refinary full of water and the production stop, so I packed water from refinary, without use senders/receivers and sink them

**Comment by psmjunior** [comment]
So, I found another way, which get rid of all fluid send to a "sink":
https://ficsit.app/mod/DHbU4UAgBzRGwx
In this way, the water that leaves the refinery and would not have space in the sender/receiver goes to limbo. But the suggestion remains, if you connect a fluid source, don't receive from a sender.

Ahh
Thanks for mod e for your attention!
