### ISSUE TITLE
(Logistics Mod) Item Sender shouldn't fill buildings inside Blueprint Designer

### ISSUE THREAD

**Issue by ghandye** [DeadMor0z/SatisfactoryMods#2]
This is might be a bug...if not, consider it an enhancement request.

The principles of the Blueprint Designer are that it shouldn't interact with the outside factory. For example, you can't attach power or belts from outside the BD into any buildings you have constructed inside the BD.

The Item Sender violates this principle, which causes some undesirable side effects. To illustrate:

1) Feed iron ore into an Item Sender (e.g. hook up output of a miner on an iron deposit, straight into an item sender)

2) Slap down a Blueprint Designer, and inside the BD, create eight smelters, each configured to produce Iron Ingots. 

3) (BUG?) Note how all eight smelters fill up with Iron Ore even when inside the Blueprint Designer.

4) Name and save the blueprint (e.g. "8x Iron Smelter"). Note how the material required to build the blueprint includes 800 Iron Ore.

5) Weep as your awesome 8x Iron Smelter blueprint now requires you to have eight stacks of Iron Ore in your inventory any time you want to deploy the blueprint

Desired behavior would be to have Item Sender ignore any buildings that are built inside Blueprint Designers.

Thanks!

**Comment by DeadMor0z** [comment]
Fixed in 1.1.2
