### ISSUE TITLE
(Logistics Mod) Item Sender/Fluid Sender will not send fuel or water to Coal Generator

### ISSUE THREAD

**Issue by ghandye** [DeadMor0z/SatisfactoryMods#3]
A few bugs with Item/Fluid Sender and Coal / Fuel Generators:

1) Coal Generators - In addition to requiring water, Coal Generators can accept multiple solid fuel types (e.g. Coal, Compacted Coal, Petroleum Coke).

In my testing, Item Senders won't send Coal or Petroleum Coke to the fuel input of a Coal Generator.

Also, Fluid Sender does not provide water to a Coal Generator, even if fuel is successfully fed in via other means.

2) Fuel Generators - These can also burn multiple types of fuel (e.g. Fuel, Liquid Biofuel, Turbofuel). Fluid Sender will not provide fuel to a Fuel Generator.

Workarounds are to use a standalone Item Receiver and Fluid Receiver and belt/pipe the goods to the generator.

TBH, I'm not sure how this would work with Item / Fluid Sender in its current incarnation, as there's no way to specify what item/fluid type you'd want to magically send to the generators...maybe it would require an enhancement of some sort.

Thanks!

**Comment by DeadMor0z** [comment]
This is by design. Senders only fill factories (buildings with recipe selection). Generators are not one of them. Use Receivers to fill with fuel of your choice.

**Comment by ghandye** [comment]
Thanks for the quick feedback! I'll close this out then.
