### ISSUE TITLE
Item Filtering does not appear to work

### ISSUE THREAD

**Issue by Fenrirthviti** [DeadMor0z/SatisfactoryMods#4]
Mod Version: 1.1.1

Expected Behavior: Typing `aluminum` in to the filter should show storage containers that have aluminum parts in them.

Observed Behavior: Typing `aluminum` in to the filter shows no results, even when it can be observed that the items are in containers that match this filter criteria.

Example: 
![image](https://github.com/DeadMor0z/SatisfactoryMods/assets/6519624/7a670abf-d139-448b-95cb-f55e52d5543b)

Container has alclad aluminum sheets in it, but when filtering for `aluminum` there are no results:
![image](https://github.com/DeadMor0z/SatisfactoryMods/assets/6519624/92570a8d-0f93-4fc2-846c-246aa3327fc7)

Additional Notes: This does not work with vanilla or modded storage containers. Searching by container name appears to work fine, just not contents as listed in the mod description.

**Comment by DeadMor0z** [comment]
Are you in single-player game?

**Comment by Fenrirthviti** [comment]
No, this is a multiplayer session.

**Comment by DeadMor0z** [comment]
Are you the host?

**Comment by DeadMor0z** [comment]
Oh, I just noticed that there is a missing note about multiplayer. Looks like I removed it accidentally, while editing descritpion.
In multiplayer, if you are not the host, there is a limitations - there is no live updates on building contents, and filter works only for building names.
I'll add it to description, sorry for that.

**Comment by Fenrirthviti** [comment]
I am not the host in this instance, I am a client. That is unfortunate that it can't work, that's a pretty critical feature. Is there a chance this may get added in the future?

**Comment by DeadMor0z** [comment]
It's by a game design - client can't access building inventory unless it begin interact with it - this is because of network optimizations. So, from client side, it is not possible to look into many inventories simultaniously.

**Comment by Fenrirthviti** [comment]
Thanks for the confirmation!
