### ISSUE TITLE
SatisManager / Scrollbar to filter list

### ISSUE THREAD

**Issue by sakoivi** [DeadMor0z/SatisfactoryMods#5]
The filter list in SatisManager mod needs a scrollbar. Please see the screenshot. Thanks for the great mod!
<img width="1021" alt="Satisfactory_Screenshot" src="https://github.com/DeadMor0z/SatisfactoryMods/assets/106589806/190b615b-2e33-4a11-a3a9-09d5b73cd44f">

**Comment by DeadMor0z** [comment]
Wow, you have a lot of different machinery)
Fixed.

**Comment by sakoivi** [comment]
Thanks for the super fast fix!
It works perfect.
MoreMilestones mod is where I got the tonz of new machines, but unfortunately it seems like the mod is discontinued. :(
https://mods.ninja/en/satisfactory/more-milestones/
