### ISSUE TITLE
[Logistics][Question] There are some speed limit in the items?

### ISSUE THREAD

**Issue by gleitoncampos** [DeadMor0z/SatisfactoryMods#6]
Hello!! I'm testing your mod Logistics together with the BAM mod, that have faster belts and more powerful machines and I noticed that the Fluid Receiver/Sender had a limitt of 607m³/min. This is a limitation or a bug?

The items tunnels and sender/receivers had a limit too? I'm testing in a scenario where I feed 5 tunnel input with 5200/min (4x 1200 + 1x 400) of coal, to feed 15 Coal generators eating 300/min, in a sum of 4500/min, and the inventory of all the 15 output are decreasing slowly and stopping after some time.

Thank you for your work, your mod are very useful!

**Comment by DeadMor0z** [comment]
There is no limit in m^3 or items, but there is a delay of 0.05sec between processing. this should be about 1200 m^3/items per min

**Comment by DeadMor0z** [comment]
Lowered delay to 0.025 in 1.1.6.

**Comment by gleitoncampos** [comment]
Wow!! Thank you very much for this!

**Comment by gleitoncampos** [comment]
Wow!! Thank you very much for this!

Tested here and is perfect now!

**Comment by gleitoncampos** [comment]
Just another question:
This delay is for the hole tunnel group? All the tunnel in group update at same time? There are any maximum number of members in a tunnel group?

**Comment by DeadMor0z** [comment]
Delay is for each input. Every input updates separately. There is no maximum.
