### ISSUE TITLE
(Logistics Mod) Exception_access_violation

### ISSUE THREAD

**Issue by TinyChad** [DeadMor0z/SatisfactoryMods#7]
It seems the game tends to crash as new items are being sent to the hub for a new milestone when selected. When the game crashes the error Exception_access_violation takes place.

**Comment by DeadMor0z** [comment]
Does it happen on latest version of mod? Did it happen before? How often does it happen?

**Comment by DeadMor0z** [comment]
Post error from game log (full execution stack)

**Comment by TinyChad** [comment]
It has taken place before and after the latest version of the mod. 

Version: 211839, IsEditor: No, IsPerforceBuild: No, BuildConfiguration: Shipping, Launcher: Steam, NetMode: Listen Server, IsUsingMods: Yes

Unhandled Exception: EXCEPTION_ACCESS_VIOLATION writing address 0x0000000000000030

FactoryGame_FactoryGame_Win64_Shipping!AFGSchematicManager::PayOffOnSchematic() [D:\BuildAgent\work\78a794e88763017d\UE4\Games\FactoryGame\Source\FactoryGame\Private\FGSchematicManager.cpp:737]
FactoryGame_FactoryGame_Win64_Shipping!AFGSchematicManager::execPayOffOnSchematic() [D:\BuildAgent\work\78a794e88763017d\UE4\Games\FactoryGame\Intermediate\Build\Win64\FactoryGame\Inc\FactoryGame\FGSchematicManager.gen.cpp:535]
FactoryGame_CoreUObject_Win64_Shipping!UFunction::Invoke() [D:\BuildAgent\work\78a794e88763017d\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\Class.cpp:5589]
FactoryGame_CoreUObject_Win64_Shipping!UObject::CallFunction() [D:\BuildAgent\work\78a794e88763017d\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:998]
FactoryGame_CoreUObject_Win64_Shipping!UObject::ProcessContextOpcode() [D:\BuildAgent\work\78a794e88763017d\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:2870]
FactoryGame_CoreUObject_Win64_Shipping!UObject::execLetBool() [D:\BuildAgent\work\78a794e88763017d\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:2771]
FactoryGame_CoreUObject_Win64_Shipping!ProcessLocalScriptFunction() [D:\BuildAgent\work\78a794e88763017d\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:1067]
FactoryGame_CoreUObject_Win64_Shipping!ProcessScriptFunction<void (__cdecl*)(UObject *,FFrame &,void *)>() [D:\BuildAgent\work\78a794e88763017d\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:898]
FactoryGame_CoreUObject_Win64_Shipping!UObject::execLocalVirtualFunction() [D:\BuildAgent\work\78a794e88763017d\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:2990]
FactoryGame_CoreUObject_Win64_Shipping!ProcessLocalScriptFunction() [D:\BuildAgent\work\78a794e88763017d\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:1067]
FactoryGame_CoreUObject_Win64_Shipping!ProcessScriptFunction<void (__cdecl*)(UObject *,FFrame &,void *)>() [D:\BuildAgent\work\78a794e88763017d\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:898]
FactoryGame_CoreUObject_Win64_Shipping!UObject::execLocalVirtualFunction() [D:\BuildAgent\work\78a794e88763017d\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:2990]
FactoryGame_CoreUObject_Win64_Shipping!ProcessLocalScriptFunction() [D:\BuildAgent\work\78a794e88763017d\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:1067]
FactoryGame_CoreUObject_Win64_Shipping!ProcessScriptFunction<void (__cdecl*)(UObject *,FFrame &,void *)>() [D:\BuildAgent\work\78a794e88763017d\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:898]
FactoryGame_CoreUObject_Win64_Shipping!UObject::execLocalVirtualFunction() [D:\BuildAgent\work\78a794e88763017d\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:2990]
FactoryGame_CoreUObject_Win64_Shipping!ProcessLocalScriptFunction() [D:\BuildAgent\work\78a794e88763017d\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:1067]
FactoryGame_CoreUObject_Win64_Shipping!ProcessScriptFunction<void (__cdecl*)(UObject *,FFrame &,void *)>() [D:\BuildAgent\work\78a794e88763017d\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:898]
FactoryGame_CoreUObject_Win64_Shipping!UObject::execLocalFinalFunction() [D:\BuildAgent\work\78a794e88763017d\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:2997]
FactoryGame_CoreUObject_Win64_Shipping!ProcessLocalScriptFunction() [D:\BuildAgent\work\78a794e88763017d\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:1067]
FactoryGame_CoreUObject_Win64_Shipping!UObject::ProcessInternal() [D:\BuildAgent\work\78a794e88763017d\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:1156]
FactoryGame_CoreUObject_Win64_Shipping!UFunction::Invoke() [D:\BuildAgent\work\78a794e88763017d\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\Class.cpp:5589]
FactoryGame_CoreUObject_Win64_Shipping!UObject::ProcessEvent() [D:\BuildAgent\work\78a794e88763017d\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\ScriptCore.cpp:1992]
FactoryGame_Engine_Win64_Shipping!AActor::ProcessEvent() [D:\BuildAgent\work\78a794e88763017d\UE4\Engine\Source\Runtime\Engine\Private\Actor.cpp:917]
FactoryGame_FactoryGame_Win64_Shipping!AFGBuildable::Factory_ReceiveTick() [D:\BuildAgent\work\78a794e88763017d\UE4\Games\FactoryGame\Intermediate\Build\Win64\FactoryGame\Inc\FactoryGame\FGBuildable.gen.cpp:841]
FactoryGame_FactoryGame_Win64_Shipping!AFGBuildableFactory::Factory_Tick() [D:\BuildAgent\work\78a794e88763017d\UE4\Games\FactoryGame\Source\FactoryGame\Private\Buildables\FGBuildableFactory.cpp:358]
FactoryGame_FactoryGame_Win64_Shipping!<lambda_ca67515999c2f313172565c8688a503d>::operator()() [D:\BuildAgent\work\78a794e88763017d\UE4\Games\FactoryGame\Source\FactoryGame\Private\FGBuildableSubsystem.cpp:561]
FactoryGame_FactoryGame_Win64_Shipping!ParallelForImpl::TParallelForData<TFunctionRef<void __cdecl(int)> >::Process() [D:\BuildAgent\work\78a794e88763017d\UE4\Engine\Source\Runtime\Core\Public\Async\ParallelFor.h:177]
FactoryGame_FactoryGame_Win64_Shipping!TGraphTask<ParallelForImpl::TParallelForTask<TFunctionRef<void __cdecl(int)> > >::ExecuteTask() [D:\BuildAgent\work\78a794e88763017d\UE4\Engine\Source\Runtime\Core\Public\Async\TaskGraphInterfaces.h:886]
FactoryGame_Core_Win64_Shipping!FTaskThreadAnyThread::ProcessTasksUntilQuit() [D:\BuildAgent\work\78a794e88763017d\UE4\Engine\Source\Runtime\Core\Private\Async\TaskGraph.cpp:887]
FactoryGame_Core_Win64_Shipping!FTaskThreadBase::Run() [D:\BuildAgent\work\78a794e88763017d\UE4\Engine\Source\Runtime\Core\Private\Async\TaskGraph.cpp:541]
FactoryGame_Core_Win64_Shipping!FRunnableThreadWin::Run() [D:\BuildAgent\work\78a794e88763017d\UE4\Engine\Source\Runtime\Core\Private\Windows\WindowsRunnableThread.cpp:86]




[FactoryGame.log](https://github.com/DeadMor0z/SatisfactoryMods/files/11668054/FactoryGame.log)

**Comment by TinyChad** [comment]
Also, it happens every time the game is played.

**Comment by DeadMor0z** [comment]
Try this one. if it works ok, I update it on ficsit.app
[Logistics.zip](https://github.com/DeadMor0z/SatisfactoryMods/files/11670085/Logistics.zip)

**Comment by DeadMor0z** [comment]
Did it help?

**Comment by DeadMor0z** [comment]
Should be fixed in 1.1.8
