### ISSUE TITLE
too much stuff sent to hub, no way of stopping

### ISSUE THREAD

**Issue by catonthekbd** [DeadMor0z/SatisfactoryMods#8]
While the Pod is delivering the items from the Hub for the previous milestone, you can select the next milestone you want.
Items then get sent to the hub automatically :)

But while the pod is away, the senders do not detect that they have sent enough, and just keep sending more stuff even though it is not needed.

The excess gets trapped inside the hub with no way of removing

Limit detection starts working again as soon as the Pod lands back on the Hub

**Comment by DeadMor0z** [comment]
Thnks for bug report! Fixed in 1.1.8
