### ISSUE TITLE
Items duplicating

### ISSUE THREAD

**Issue by Jaden-Adonis** [DeadMor0z/SatisfactoryMods#9]
Hey man, I was playing around with the senders and I found that every time the sender sent stone to my two constructors it would duplicate the stone sending it to both constructors. 

Setup:

Mk I miner ==> Item sender ==> 2 x Constructors

**Comment by DeadMor0z** [comment]
Can you confirm that having 10 stones (for example) in Item Sender will end up having 10 stoens in each constructor? Disconnect sender from miner, put stones and check if they were really duplicated

**Comment by Jaden-Adonis** [comment]
Hey DeadMor0z,

I'm sorry for wasting your time. I didn't realize I had a mod doubling my belt speed (have since removed). So I was getting the full 120 instead of the 60 I thought I had. 

I hope it didn't stress you out.

**Comment by DeadMor0z** [comment]
No problem at all!
